interface: wg0  # WireGuard interface to manage

kms: 
  uri: "https://127.0.0.1:8443/api/v1/keys" # KMS URI
  certificate: private/certs/sae_001.crt    # SAE certificate
  root_certificate: private/certs/root.crt  # Root CA certificate
  secret_key: private/certs/sae_001.key     # SAE secret key
  sae: sae_001                              # SAE ID
  interface: 14                             # KMS interface (4 for ETSI QKD 004, 14 for ETSI QKD 014)

# Port where the rotator will be exposed to its peers on the specified WireGuard's interface 
port: 2345

secret_auth_key: private/priv.key # Authentication secret keys

# Information about the peers
peers:
  - 9OmSKzF5QHD5mckhBHyoN2uPPRGJNDYOl15+DKbtV1M=: # ID (public key) of the peer
      public_auth_key: pub_0.key
      ip: 10.0.0.2      # IP of the peer
      port: 2347        # Port of the peer rotator
      sae: sae_002      # SAE of the peer in the KMS
      mode: client      # Mode (client/server)
      extra_handshakes: # PQ extra handshakes
      - ML_KEM_512
  - 12mSKzF5QHd57ckhBHyoN2uPPRGJNDYOl15+dfbt19L=: # Another peer
      public_auth_key: pub_1.key
      ip: 10.0.0.3
      port: 3456
      sae: sae_003
      mode: server