[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "wg-Qrotator"
version = "0.1.1"
description = "The quantum-enabled hybrid key rotator for WireGuard tunnels."
authors = [
  { name = "Diogo Filipe Matos", email = "dftm@ua.pt" },
  { name = "Armando Nolasco Pinto", email = "anp@ua.pt" },
]
maintainers = [{ name = "Diogo Filipe Matos", email = "dftm@ua.pt" }]
dependencies = [
  "wolfcrypt==5.8.2.post0",
  "PyYAML==6.0.2",
  "requests==2.32.5",
  "schema==0.7.7",
  "psutil==7.1.0",
  "filelock==3.19.1",
  "keyring==25.6.0",
  "keyrings.alt==5.0.2",
  "pycryptodome==3.23.0",
]
requires-python = ">= 3.10"
readme = "README.md"
license = "AGPL-3.0"
license-files = ["LICEN[CS]E.*"]
keywords = [
  "key rotator",
  "quantum",
  "QKD",
  "post-quantum",
  "PQC",
  "tunneling",
  "VPN",
]

[project.urls]
Documentation = "https://quantum-communication-group.github.io/wg-Qrotator"
Repository = "https://github.com/Quantum-Communication-Group/wg-Qrotator"
"Bug Tracker" = "https://github.com/Quantum-Communication-Group/wg-Qrotator/issues"

[project.scripts]
wg-qrotator = "wg_qrotator.cli:main"
