title: wg-Qrotator
description: The quantum-enabled hybrid key rotator for WireGuard tunnels.
theme: just-the-docs
color_scheme: dark

mermaid:
  version: "11.12.0"

url: https://wg-Qrotator.github.io

aux_links:
  "wg-Qrotator on GitHub":
    - "//github.com/Quantum-Communication-Group/wg-Qrotator"

#logo: "/assets/imagem.png"                 # to add
#favicon_ico: "/assets/images/favicon.ico"  # to add

last_edit_timestamp: true
gh_edit_link: true
gh_edit_link_text: "Edit this page on GitHub."
gh_edit_repository: "https://github.com/Quantum-Communication-Group/wg-Qrotator"
gh_edit_branch: "main/docs" 
gh_edit_view_mode: "tree"

callouts:
  warning:
    title: Warning
    color: yellow
  tip:
    title: Tip
    color: blue
  disclaimer:
    title: Disclaimer
    color: red

nav_external_links:
  - title: IT Av Quantum Communication Group
    url: https://www.it.pt/Groups/Index/72
    hide_icon: false
    opens_in_new_tab: true 